### ISSUE TITLE
Improved boss JSONs

### ISSUE THREAD

**Issue by EliphasNUIT** [stellarashes/gw2-raid-discord-bot#1]
Hello Stellarashes,

I'd like to propose an enhancement to the bot, as I find copy/pasting (or pre-writing) !start dhuum name1 name2 name3 a little bit tedious, particularly if you are often wiping. What do you think about putting this information directly in the JSON? For example:
```
// Green Guys
{
      "startTime": x,
      "interval": x,
      "playersInvolved": [
        "Green Dude 1", 
        "Green Dude 2", 
        "Green Dude 3"
      ],
      "mechanicNames": [
        "Arrow",
        "Circle",
        ...
      ],
      "warnTime": x
},

```

This would make the bot even more flexible and we'd be able to add something like this to Dhuum:
```
// Make the tank move
{
      "startTime": x,
      "interval": x,
      "playersInvolved": ["Tank Dude"],
      "mechanicNames": [
        "North",
        "Middle",
        ...
      ],
      "warnTime": x
},
```

What do you think? I believe this should make the bot more confortable to use particularly for statics where the roles are fixed. It would also solve the limitation where we can't put multiple mechanics with players involved on a single boss.

**Comment by stellarashes** [comment]
Yeah, that sounds like a good idea.  I'll implement this later today.

**Comment by stellarashes** [comment]
Should be implemented by the latest commit, but I'm going to work and I'll have to check to make sure this works correctly later today (and also recompile a release)

**Comment by stellarashes** [comment]
Also just to note, if you have multiple playersInvolved set, doing !start [boss] [name 1] will give you very strange results, because any name you specify as a part of the start command will override the player name for ALL mechanics.  So if you do set the names, you should start the bot without any name overrides.

**Comment by stellarashes** [comment]
Okay this should be up at https://github.com/stellarashes/gw2-raid-discord-bot/releases/tag/0.02 ; let me know if it doesn't work right
