### ISSUE TITLE
Error occurred (get key failed from google)

### ISSUE THREAD

**Issue by gabeaventh** [stellarashes/gw2-raid-discord-bot#3]
i dont know the bot is still functioning for you or not, but i experienced that for couple of weeks, and can get the bots to say anything, it can join, as soon as i type !startnow dhuum bla bla bla command, it says:

Error occurred (get key failed from google) in the chat box

![botpict](https://user-images.githubusercontent.com/7519522/46572151-3b859180-c9ab-11e8-86f8-c5ac0cc24535.PNG)

i think theres a problem from your Google TTS API, im trying to fix it by downloading the master files and trying to replace the API with my own API, but i got binding.gyp is not found, trying to fix the issue but im new with node.js, and trying all the solutions on the internet, but nothing works

**Comment by stellarashes** [comment]
Yeah someone told me about this a week or so ago, but I ended up keep on being busy with other things.  Anyways I've updated that and here's the new release: https://github.com/stellarashes/gw2-raid-discord-bot/releases/tag/0.0.5
