### ISSUE TITLE
Error occurred (get key failed from google)

### ISSUE THREAD

**Issue by vortex1409** [stellarashes/gw2-raid-discord-bot#4]
`
Error: get key failed from google
    at C:\snapshot\gw2-raid-discord-bot\node_modules\google-tts-api\lib\key.js:23:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: get key failed from google
    at C:\snapshot\gw2-raid-discord-bot\node_modules\google-tts-api\lib\key.js:23:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
done
Error: get key failed from google
    at C:\snapshot\gw2-raid-discord-bot\node_modules\google-tts-api\lib\key.js:23:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: get key failed from google
    at C:\snapshot\gw2-raid-discord-bot\node_modules\google-tts-api\lib\key.js:23:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
`

**Comment by stellarashes** [comment]
Updated 
https://github.com/stellarashes/gw2-raid-discord-bot/releases/tag/0.0.6
